### ISSUE TITLE
sp changes

### ISSUE THREAD

**Issue by willgearty** [rspatial/geosphere#13]
Loading the package now results in the following message:
```r
The legacy packages maptools, rgdal, and rgeos, underpinning this package
will retire shortly. Please refer to R-spatial evolution reports on
https://r-spatial.org/r/2023/05/15/evolution4.html for details.
This package is now running under evolution status 0 
```

More details: https://r-spatial.org/r/2023/05/15/evolution4.html

Is there any intent on fixing `geosphere` as described in the above blog post?

**Comment by rhijmans** [comment]
That is a somewhat misleading message as sp does not depend on any of these packages. I do not think there is anything that must be fixed. On the long run I will probably remove support for sp classes.

**Comment by Allan-Engelhardt-BW** [comment]
Setting the option described here https://r-spatial.org/r/2023/05/15/evolution4.html#sp-evolution-status removes the warning. The users of {geosphere} can apply this as a forward-compatible workaround for the warning.

```
options("sp_evolution_status" = 2)
```
