### ISSUE TITLE
Calculating shortest distance between two points but avoid crossing the land

### ISSUE THREAD

**Issue by Nicolescm** [rspatial/geosphere#16]
Hello

I was wondering if there is a package function that allows me to calculate the distance between two points, but avoiding that the trajectory passes over continent?

Thank you :)

**Comment by mdsumner** [comment]
I wrote an implementation of this here, terrible package name but I haven't had a better idea yet: 

https://github.com/mdsumner/noswimming


(I think it's too specific for geosphere, it's really about a choice of a data set and a few domain-specific assumptions about what is needed, here following a particular contour in a raster dataset relevant to the domain of the moving item)

Hit me up at that repo if you need help

**Comment by rhijmans** [comment]
With raster data you may also consider `terra::gridDist`

**Comment by rhijmans** [comment]
Or you can use the "gdistance" package
